//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CheckApply
    {
        public string ApplyID { get; set; }
        public string PersonID { get; set; }
        public string Phone { get; set; }
        public string CheckCode { get; set; }
        public Nullable<int> ApplyState { get; set; }
        public int TaskType { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
