//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MiddleProduct
    {
        public string MProductID { get; set; }
        public string MCompanyCode { get; set; }
        public string PCompanyCode { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int ProductState { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
