//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Order
    {
        public string OrderCode { get; set; }
        public string SendPerson { get; set; }
        public string SendCompany { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string ReceivePerson { get; set; }
        public string ReceiveCompany { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
        public string ReProductPerson { get; set; }
        public Nullable<System.DateTime> ReProductTime { get; set; }
        public string CheckPerson { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public int OrderState { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
