//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Person
    {
        public string PersonID { get; set; }
        public string LogID { get; set; }
        public string PersonName { get; set; }
        public string PersonPhoto { get; set; }
        public string PersonPhone { get; set; }
        public string PersonPwd { get; set; }
        public string CompanyCode { get; set; }
        public int RoleType { get; set; }
        public System.DateTime AccountBegin { get; set; }
        public System.DateTime AccountEnd { get; set; }
        public int AccountState { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string MsgCode { get; set; }
        public Nullable<int> MobileType { get; set; }
    }
}
