//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_RelationApply
    {
        public string ApplyCode { get; set; }
        public string SPersonID { get; set; }
        public string SCompanyCode { get; set; }
        public string RCompanyCode { get; set; }
        public int ApplyType { get; set; }
        public int ApplyState { get; set; }
        public string ApplyContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CheckPerson { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
    }
}
