//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AccountApply
    {
        public string ApplyCode { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyImage { get; set; }
        public int CompanyType { get; set; }
        public int ApplyType { get; set; }
        public int AccountCount { get; set; }
        public int UseTime { get; set; }
        public string LinkMan { get; set; }
        public string LinkPhone { get; set; }
        public string Tel { get; set; }
        public decimal TotalBalance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int IsPaid { get; set; }
        public Nullable<int> PayWay { get; set; }
        public string PayAccount { get; set; }
        public string PayCode { get; set; }
        public int ApplyState { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
