//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Message
    {
        public string MsgID { get; set; }
        public string ReceiveID { get; set; }
        public int ReceiverType { get; set; }
        public string MsgTitle { get; set; }
        public string MsgContent { get; set; }
        public int MsgState { get; set; }
        public int SendType { get; set; }
        public Nullable<int> MsgType { get; set; }
        public Nullable<int> IsPay { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Updator { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
