//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenter.Data.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_ProductType
    {
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public int ShowOrder { get; set; }
        public int NodeLevel { get; set; }
        public string ParentCode { get; set; }
        public string UniteCode { get; set; }
    }
}
