//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenterStandard
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_OrderMain
    {
        public System.Guid UID { get; set; }
        public string OrderNum { get; set; }
        public string UsePersonName { get; set; }
        public string Phone { get; set; }
        public string ReceivePerson { get; set; }
        public Nullable<int> State { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OrderState { get; set; }
        public DateTime AddDate { get; set; }
    }
}
