//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderCenterStandard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderCentEntities : DbContext
    {
        public OrderCentEntities()
            : base("name=OrderCentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<O_CommodityInfo> O_CommodityInfo { get; set; }
        public virtual DbSet<O_FoodType> O_FoodType { get; set; }
        public virtual DbSet<O_OrderMain> O_OrderMain { get; set; }
        public virtual DbSet<O_Unit> O_Unit { get; set; }
        public virtual DbSet<O_UserInfo> O_UserInfo { get; set; }
        public virtual DbSet<O_OrderDetail> O_OrderDetail { get; set; }
    }
}
